import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#EEEEEE" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#26324A",
    paddingTop: 40,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  logoCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  logoText: { fontWeight: "bold", fontSize: 16, color: "#26324A" },
  headerTitle: { color: "#fff", fontSize: 20, fontWeight: "bold" },
  content: { padding: 12, paddingBottom: 80 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  menuBox: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 8,
    marginHorizontal: 4,
    padding: 12,
    alignItems: "flex-start",
    justifyContent: "center",
    minHeight: 70,
    borderRightWidth: 20,
    position: "relative",
    overflow: "hidden",
  },
  menuIcon: { fontSize: 28, marginBottom: 4 },
  menuTitle: { fontSize: 14, fontWeight: "bold", color: "#26324A" },
  menuSideBar: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  bigButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    marginHorizontal: 4,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderWidth: 2,
    justifyContent: "center",
  },
  bigButtonIcon: { fontSize: 22, marginRight: 8 },
  bigButtonText: { fontSize: 16, fontWeight: "bold" },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "#26324A",
    height: 75,
    alignItems: "center",
    justifyContent: "space-around",
    // borderTopLeftRadius: 16,
    // borderTopRightRadius: 16,
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  navItem: { alignItems: "center", flex: 1 },
  navIcon: { fontSize: 28, color: "#fff" },
  navLabel: { fontSize: 13, color: "#fff", marginTop: 4 },
});

export default styles;
