import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100, // Klavye bindirme durumunda içeriğin görünür kalması için
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F7FA",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#555",
  },
  header: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#2C3E50",
    textAlign: "center",
    marginBottom: 25,
  },
  section: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#34495E",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ECEFF1",
    paddingBottom: 10,
  },
  input: {
    height: 50,
    borderColor: "#BDC3C7",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 15,
    paddingHorizontal: 15,
    backgroundColor: "#FFFFFF",
    fontSize: 16,
    color: "#34495E",
  },
  selectCustomerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3498DB",
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  selectCustomerButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  clearCustomerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E74C3C",
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  clearCustomerButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  dateButton: {
    backgroundColor: "#ECF0F1",
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
  },
  dateButtonText: {
    fontSize: 16,
    color: "#34495E",
    fontWeight: "500",
  },
  itemRowVertical: {
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ECEFF1",
    paddingBottom: 10,
  },
  pickerContainer: {
    borderColor: "#BDC3C7",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: "#FFFFFF",
    overflow: "hidden", // Android'de picker'ın kenarlarını düzeltir
  },
  picker: {
    height: 50,
    width: "100%",
    color: "#34495E",
  },
  pickerItem: {
    fontSize: 16,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  smallInput: {
    flex: 1,
    height: 45,
    borderColor: "#BDC3C7",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
    fontSize: 15,
    color: "#34495E",
    marginRight: 10,
  },
  lineTotalText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2C3E50",
    minWidth: 80, // Minimum genişlik vererek düzeni koru
    textAlign: "right",
  },
  removeButton: {
    marginLeft: 10,
    padding: 5,
  },
  addItemButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#28A745",
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  addItemButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  totalAmountText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2C3E50",
    marginBottom: 10,
  },
  remainingAmountText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#E74C3C",
    marginBottom: 10,
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2C3E50",
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    marginBottom: 30, // Alt kısımda boşluk bırak
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  // Yeni eklenen stiller (zaten vardı, tekrar ekledim tutarlılık için)
  driverPickerContainer: {
    borderColor: "#BDC3C7",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 15,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  driverPicker: {
    height: 50,
    width: "100%",
    color: "#34495E",
  },
  noDriversText: {
    fontSize: 14,
    color: "#E74C3C",
    marginBottom: 15,
    textAlign: "center",
  },
});

export default styles;
